port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
keep-alive-interval: 60
dns:
  enable: true
  ipv6: false
  default-nameserver: [223.5.5.5, 119.29.29.29]
  fake-ip-range: 198.18.0.1/16
  use-hosts: true
  nameserver: ["https://doh.pub/dns-query", "https://dns.alidns.com/dns-query"]
  fallback:
    [
      "https://doh.dns.sb/dns-query",
      "https://dns.cloudflare.com/dns-query",
      "https://dns.twnic.tw/dns-query",
      "tls://8.8.4.4:853",
    ]
  fallback-filter: { geoip: true, ipcidr: [240.0.0.0/4, 0.0.0.0/32] }
proxies:
  - {
      name: VPS HK - Azure2,
      type: vmess,
      server: debianforlove98.eastasia.cloudapp.azure.com,
      port: 25397,
      uuid: bffd9dec-4d4f-440f-90fd-6b4802902c47,
      alterId: 0,
      cipher: auto,
      skip-cert-verify: true,
      udp: false,
      network: ws,
      tls: true,
      ws-opts: { path: /, headers: { Host: tms.dingtalk.com } },
      ws-path: /,
      ws-headers: { Host: tms.dingtalk.com },
    }
  - {
      name: VPS HK - AzureLifeng,
      type: vmess,
      server: 20.187.69.152,
      port: 56791,
      alterId: 0,
      uuid: e398819f-fb5a-479d-fe26-c2d416da6737,
      cipher: auto,
      udp: false,
    }
proxy-providers:
  Night:
    type: http
    path: ./profiles/r0axwlFh6SCR.yaml
    url: "https://sub.download-hiccup.xyz/api/v1/client/subscribe?token=3d89aa26446b9b53aa8abbe90ec36d76"
    interval: 86400
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 1800
      timeout: 5
  

#proxies:

proxy-groups:
  - name: 🖐节点选择🖐
    type: select
    url: "http://www.gstatic.com/generate_204"
    use:
      - Night
    filter: "^(?!.*台湾).*"
    proxies:
      - VPS HK - Azure2
      - VPS HK - AzureLifeng
    interval: 1800
  - name: ❤是大流量❤
    type: url-test
    url: "http://www.gstatic.com/generate_204"
    use:
      - fanqiang
    interval: 600
    filter: ^(?!.*(?:port|IP|CF|剩余|套餐)).*$
  - name: 😎美国服务我😎
    type: select
    url: "http://www.gstatic.com/generate_204"
    use:
      - Night
    filter: "(.美国.)"

rule-providers:
  reject:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt"
    path: ./ruleset/reject.yaml
    interval: 86400

  icloud:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt"
    path: ./ruleset/icloud.yaml
    interval: 86400

  apple:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt"
    path: ./ruleset/apple.yaml
    interval: 86400

  google:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/google.txt"
    path: ./ruleset/google.yaml
    interval: 86400

  proxy:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt"
    path: ./ruleset/proxy.yaml
    interval: 86400

  direct:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt"
    path: ./ruleset/direct.yaml
    interval: 86400

  private:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/private.txt"
    path: ./ruleset/private.yaml
    interval: 86400

  gfw:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt"
    path: ./ruleset/gfw.yaml
    interval: 86400

  tld-not-cn:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/tld-not-cn.txt"
    path: ./ruleset/tld-not-cn.yaml
    interval: 86400

  telegramcidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt"
    path: ./ruleset/telegramcidr.yaml
    interval: 86400

  cncidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt"
    path: ./ruleset/cncidr.yaml
    interval: 86400

  lancidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt"
    path: ./ruleset/lancidr.yaml
    interval: 86400

  applications:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/applications.txt"
    path: ./ruleset/applications.yaml
    interval: 86400
  
  ##Default Setting(Direct or REJECT) provided by Github Project: clash-rules
  - RULE-SET,applications,DIRECT
  - RULE-SET,private,DIRECT
  - RULE-SET,reject,REJECT
  - RULE-SET,icloud,DIRECT
  - RULE-SET,apple,DIRECT
  - RULE-SET,direct,DIRECT
  - RULE-SET,lancidr,DIRECT
  - RULE-SET,cncidr,DIRECT
  - RULE-SET,cn_ads_remove,REJECT
  ## Self-Added
  ## With direct domain
  - "DOMAIN-SUFFIX,e.wxriw.cn,DIRECT"
  - "DOMAIN-SUFFIX,twitch.tv,❤是大流量❤"
  - "DOMAIN-SUFFIX,twitchcdn.net,❤是大流量❤"
  - DOMAIN-SUFFIX,openai.com,😎美国服务我😎
  - DOMAIN-SUFFIX,phind.com,😎美国服务我😎
  - DOMAIN-SUFFIX,readwise.io,😎美国服务我😎
  - DOMAIN-SUFFIX,google.com,😎美国服务我😎
  - DOMAIN-KEYWORD,microsoft,😎美国服务我😎
  - DOMAIN-KEYWORD,azure,😎美国服务我😎
  - DOMAIN-KEYWORD,shortwave,😎美国服务我😎
  - DOMAIN-KEYWORD,cloudflare,😎美国服务我😎
  - DOMAIN-KEYWORD,stripe,😎美国服务我😎
  ## Sporify
  - "DOMAIN-KEYWORD,-spotify-com,😎美国服务我😎"
  - "DOMAIN-KEYWORD,spotify.com,😎美国服务我😎"
  - "DOMAIN-SUFFIX,spotify.com,😎美国服务我😎"
  - "DOMAIN-SUFFIX,spotifycdn.com,😎美国服务我😎"
  - "DOMAIN-SUFFIX,spotifycdn.net,😎美国服务我😎"
  ## Youtube Music
  - "PROCESS-NAME,com.google.android.apps.youtube.music,😎美国服务我😎"
  - "PROCESS-NAME,com.google.android.youtube.tvmusicroot,😎美国服务我😎"
  - "PROCESS-NAME,com.vanced.android.apps.youtube.music,😎美国服务我😎"
  ## Youtube related
  - "DOMAIN-KEYWORD,youtube,❤是大流量❤"
  - "DOMAIN-KEYWORD,youtube,❤是大流量❤"
  - "DOMAIN,youtubei.googleapis.com,❤是大流量❤"
  - "DOMAIN,yt3.ggpht.com,❤是大流量❤"
  - "DOMAIN-SUFFIX,googlevideo.com,❤是大流量❤"
  - "DOMAIN-SUFFIX,gvt2.com,❤是大流量❤"
  - "DOMAIN-SUFFIX,youtu.be,❤是大流量❤"
  - "DOMAIN-SUFFIX,youtube.com,❤是大流量❤"
  - "DOMAIN-SUFFIX,ytimg.com,❤是大流量❤"
  ## Discord
  - "DOMAIN-SUFFIX,discord.co,😎美国服务我😎"
  - "DOMAIN-SUFFIX,discord.com,😎美国服务我😎"
  - "DOMAIN-SUFFIX,discord.gg,😎美国服务我😎"
  - "DOMAIN-SUFFIX,discord.media,😎美国服务我😎"
  - "DOMAIN-SUFFIX,discordapp.com,😎美国服务我😎"
  - "DOMAIN-SUFFIX,discordapp.net,😎美国服务我😎"

  - "DOMAIN-SUFFIX,reddit.com,😎美国服务我😎"
  - "DOMAIN-SUFFIX,redditlist.com,😎美国服务我😎"
  - "DOMAIN-SUFFIX,redditmedia.com,😎美国服务我😎"
  - "DOMAIN-SUFFIX,redditstatic.com,😎美国服务我😎"
  ## Twitter
  - "DOMAIN-KEYWORD,twitter,😎美国服务我😎"
  - "DOMAIN-SUFFIX,twitter.com,😎美国服务我😎"
  - "DOMAIN-SUFFIX,twitter.jp,😎美国服务我😎"
  - "DOMAIN-SUFFIX,twitter4j.org,😎美国服务我😎"
  - "DOMAIN-SUFFIX,twittercounter.com,😎美国服务我😎"
  - "DOMAIN-SUFFIX,twitterfeed.com,😎美国服务我😎"
  - "DOMAIN-SUFFIX,twittergadget.com,😎美国服务我😎"
  - "DOMAIN-SUFFIX,twitterkr.com,😎美国服务我😎"
  - "DOMAIN-SUFFIX,twittermail.com,😎美国服务我😎"
  - "DOMAIN-SUFFIX,twitterrific.com,😎美国服务我😎"
  - "DOMAIN-SUFFIX,twittertim.es,😎美国服务我😎"
  ## Without, rule-provider
  - RULE-SET,telegramcidr,❤是大流量❤
  - RULE-SET,proxy,🖐节点选择🖐
  ##应用净化

  - MATCH,🖐节点选择🖐

secret: 15f775eb-667d-408c-8b3f-0bc059c93788
